version: "3.5"
services:
    hub:
        image: selenium/hub
        container_name: hub
        ports: 
          -  "4444:4444"
        networks:
          -  my-network-name
    chrome:
        image: selenium/node-chrome
        depends_on: 
          -  hub
        volumes:
          -  /dev/shm:/dev/shm/
        environment: 
          -  HUB_HOST=hub
          -  HUB_PORT=4444
        networks:
          -  my-network-name

networks:
  my-network-name:
    name: grid
